# Generated by Django 3.2 on 2021-05-13 19:47

from django.conf import settings
import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16, verbose_name='Имя категории')),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='CreatorCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Название компании')),
                ('image', models.ImageField(storage=django.core.files.storage.FileSystemStorage(location=None), upload_to='static/games/images/company', verbose_name='Логотип')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='Дата регистрации')),
            ],
        ),
        migrations.CreateModel(
            name='CreatorGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(default=0, verbose_name='Рейтинг')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('company', models.ManyToManyField(blank=True, to='games.CreatorCompany', verbose_name='Компания')),
            ],
        ),
        migrations.CreateModel(
            name='TagsGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16, verbose_name='Имя тега')),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, verbose_name='Название')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('image', models.ImageField(storage=django.core.files.storage.FileSystemStorage(location=None), upload_to='static/games/images', verbose_name='Иконка')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('iframe', models.URLField(verbose_name='Ссылка на IFrame')),
                ('is_release', models.BooleanField(default=False, verbose_name='Публичный доступ')),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.creatorgame', verbose_name='Автор')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.categorygame', verbose_name='Категория')),
                ('company', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='games.creatorcompany', verbose_name='Компания')),
                ('tags', models.ManyToManyField(blank=True, to='games.TagsGame', verbose_name='Теги')),
            ],
        ),
        migrations.AddField(
            model_name='creatorcompany',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.creatorgame', verbose_name='Руководитель'),
        ),
    ]
