# Generated by Django 3.2 on 2021-05-13 20:54

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creatorcompany',
            name='image',
            field=models.ImageField(height_field=128, storage=django.core.files.storage.FileSystemStorage(location=None), upload_to='static/games/images/company', verbose_name='Логотип', width_field=128),
        ),
        migrations.AlterField(
            model_name='game',
            name='image',
            field=models.ImageField(height_field=180, storage=django.core.files.storage.FileSystemStorage(location=None), upload_to='static/games/images', verbose_name='Иконка', width_field=135),
        ),
    ]
