# Generated by Django 3.2 on 2021-05-23 18:55

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_auto_20210523_0136'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='user_views',
            field=models.IntegerField(default=0, verbose_name='Количество просмотров'),
        ),
        migrations.AlterField(
            model_name='creatorcompany',
            name='image',
            field=models.ImageField(storage=django.core.files.storage.FileSystemStorage(location='F:\\projects\\WebPP\\site\\CSOL\\media/'), upload_to='games/company', verbose_name='Логотип'),
        ),
        migrations.AlterField(
            model_name='game',
            name='image',
            field=models.ImageField(blank=True, storage=django.core.files.storage.FileSystemStorage(location='F:\\projects\\WebPP\\site\\CSOL\\media/'), upload_to='games/images', verbose_name='Иконка'),
        ),
    ]
