# Generated by Django 3.2 on 2021-05-26 09:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20210522_2327'),
        ('games', '0009_remove_comment_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favoritegames',
            name='profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.profile', verbose_name='Пользователь'),
        ),
    ]
