# Generated by Django 3.2 on 2021-05-27 00:22

import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_profile_photo'),
        ('games', '0010_alter_favoritegames_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creatorcompany',
            name='image',
            field=models.ImageField(default='site/no_photo.png', storage=django.core.files.storage.FileSystemStorage(location='F:\\projects\\WebPP\\site\\CSOL\\media/'), upload_to='games/company', verbose_name='Логотип'),
        ),
        migrations.AlterField(
            model_name='game',
            name='image',
            field=models.ImageField(blank=True, default='site/no_photo_game.jpg', storage=django.core.files.storage.FileSystemStorage(location='F:\\projects\\WebPP\\site\\CSOL\\media/'), upload_to='games/images', verbose_name='Иконка'),
        ),
        migrations.CreateModel(
            name='GameLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.game')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.profile')),
            ],
            options={
                'unique_together': {('game', 'user')},
            },
        ),
    ]
