# Generated by Django 3.2 on 2021-05-27 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_friend_current_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(blank=True, default='site/no_photo.png', upload_to='users/', verbose_name='Фотография'),
        ),
    ]
